// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/19/2025, 9:42:43 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/user/copy/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/user/copy/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/user/copy/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/user/copy/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/user/copy/plugins/**/*.{js,ts,mjs}","/home/user/copy/composables/**/*.{js,ts,mjs}","/home/user/copy/utils/**/*.{js,ts,mjs}","/home/user/copy/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/user/copy/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/user/copy/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/user/copy/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;